apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cw2app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw2app
  template:
    metadata:
      labels:
        app: cw2app
    spec:
      containers:
        - name: cw2app-container
          image: safridigcu/cw2-server:latest  # <-- match Jenkins build
          imagePullPolicy: Always              # <-- force pull every time
          ports:
            - containerPort: 8080   

---
apiVersion: v1
kind: Service
metadata:
  name: cw2app-service
spec:
  selector:
    app: cw2app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   
  type: NodePort
