apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw2app
  template:
    metadata:
      labels:
        app: cw2app
    spec:
      containers:
        - name: cw2app-container
          image: safridigcu/cw2app:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cw2app-service
spec:
  selector:
    app: cw2app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
