apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw2-server
  template:
    metadata:
      labels:
        app: cw2-server
    spec:
      containers:
      - name: cw2-server
        image: safridigcu/cw2-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: cw2-server-service
spec:
  type: NodePort
  selector:
    app: cw2-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31355  # Optional: Keep fixed if you want to re-use the same NodePort
